# Generated by Django 2.1.7 on 2019-02-24 03:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RobotApplicationUnderTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Designates when this thing was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Designates when this thing was last modified.')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('app_test_location', models.FilePathField(allow_files=False, allow_folders=True, default='/Users/mrose/ws/robotframework', editable=False, help_text='The local path to the directory that contains Robot tests for this app. Defaults to ROBOT_PROJECT_PATH env variable.', max_length=200, path='/Users/mrose/ws/robotframework', recursive=True)),
                ('robot_location', models.FileField(help_text='Select the local robot executable to use when running the tests for this application.', max_length=200, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RobotTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Designates when this thing was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Designates when this thing was last modified.')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_robot_tag', related_query_name='parent_application', to='testrunner.RobotApplicationUnderTest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RobotTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Designates when this thing was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Designates when this thing was last modified.')),
                ('documentation', models.TextField(max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotTestEnvironment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Designates when this thing was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Designates when this thing was last modified.')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('host_url', models.URLField(help_text='The base URL to use for testing this application.', verbose_name='Web URL')),
                ('for_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_test_environment', related_query_name='for_application', to='testrunner.RobotApplicationUnderTest', verbose_name='Test environment for')),
            ],
        ),
        migrations.CreateModel(
            name='RobotTestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('error', 'ERROR')], help_text='The final result of the test execution.', max_length=5)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When test execution started.')),
                ('end_time', models.DateTimeField(help_text='When test execution ended.')),
                ('execution_time', models.TimeField()),
                ('status', models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], help_text='The current status of this test run.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why the test run has the current status.', max_length=400)),
                ('robot_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testrunner.RobotTest')),
            ],
        ),
        migrations.CreateModel(
            name='RobotTestStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Designates when this thing was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Designates when this thing was last modified.')),
                ('keyword', models.CharField(max_length=200)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='execution order')),
                ('arguments', models.TextField(blank=True, help_text='A list of arguments passed to the test step keyword with a line break between each.', max_length=4000, null=True)),
                ('robot_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testrunner.RobotTest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RobotTestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Designates when this thing was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Designates when this thing was last modified.')),
                ('documentation', models.TextField(max_length=4000, null=True)),
                ('suite_location', models.FilePathField(allow_folders=True, default='/Users/mrose/ws/robotframework', editable=False, help_text='The local path to the directory or file that contains tests for this suite. Options to select this will populate after an application is selected and saved.', max_length=200, path='/Users/mrose/ws/robotframework', recursive=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_suite', related_query_name='parent_application', to='testrunner.RobotApplicationUnderTest')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_suite', related_query_name='parent_suite', to='testrunner.RobotTestSuite')),
                ('robot_tags', models.ManyToManyField(blank=True, to='testrunner.RobotTag')),
            ],
        ),
        migrations.CreateModel(
            name='RobotVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Designates when this thing was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Designates when this thing was last modified.')),
                ('description', models.TextField(blank=True, max_length=4000, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_robot_variable', related_query_name='parent_application', to='testrunner.RobotApplicationUnderTest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='robottest',
            name='robot_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', related_query_name='suite', to='testrunner.RobotTestSuite'),
        ),
        migrations.AddField(
            model_name='robottest',
            name='robot_tags',
            field=models.ManyToManyField(blank=True, to='testrunner.RobotTag'),
        ),
        migrations.AlterUniqueTogether(
            name='robottestsuite',
            unique_together={('application', 'parent', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='robottestenvironment',
            unique_together={('for_application', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='robottest',
            unique_together={('robot_suite', 'name')},
        ),
    ]
