# Generated by Django 2.1.7 on 2019-02-16 01:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('error', 'ERROR')], max_length=5)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('execution_time', models.TimeField()),
                ('status', models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], max_length=20)),
                ('reason', models.TextField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testrunner.BaseObject')),
                ('documentation', models.TextField(max_length=4000, null=True)),
            ],
            bases=('testrunner.baseobject',),
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testrunner.BaseObject')),
                ('documentation', models.TextField(max_length=4000, null=True)),
                ('test_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            bases=('testrunner.baseobject',),
        ),
        migrations.AddField(
            model_name='testrun',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testrunner.Test'),
        ),
        migrations.AddField(
            model_name='test',
            name='suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', related_query_name='suite', to='testrunner.TestSuite'),
        ),
    ]
