# Generated by Django 2.1.7 on 2019-02-20 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotapplicationundertest',
            name='app_test_location',
            field=models.FilePathField(allow_files=False, allow_folders=True, help_text='The local path to the directory that contains tests for this app.', max_length=200, path='C:\\Users\\mrose\\ws\\robotframework', recursive=True),
        ),
        migrations.AlterField(
            model_name='robotapplicationundertest',
            name='robot_location',
            field=models.FilePathField(help_text='The local path to the robot executable to use when running the tests for this application.', match='^.*.exe.*$', max_length=200, path='C:\\Users\\mrose\\ws\\robotframework', recursive=True),
        ),
        migrations.AlterField(
            model_name='robottag',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='robottest',
            name='robot_suite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', related_query_name='suite', to='testrunner.RobotTestSuite'),
        ),
        migrations.AlterField(
            model_name='robottestsuite',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_suite', related_query_name='parent_application', to='testrunner.RobotApplicationUnderTest'),
        ),
        migrations.AlterField(
            model_name='robottestsuite',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_suite', related_query_name='parent_suite', to='testrunner.RobotTestSuite'),
        ),
        migrations.AlterField(
            model_name='robottestsuite',
            name='suite_location',
            field=models.FilePathField(allow_folders=True, blank=True, help_text='The local path to the directory or file that contains tests for this suite. Options to select this will populate after an application is selected and saved.', max_length=200, path='C:\\Users\\mrose\\ws\\robotframework\\SnowRF\\SNOW', recursive=True),
        ),
        migrations.AlterField(
            model_name='robotvariable',
            name='description',
            field=models.TextField(blank=True, max_length=4000, null=True),
        ),
    ]
