# Generated by Django 2.1.7 on 2019-03-04 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='robotapplicationundertest',
            options={'verbose_name': 'Robot application under test', 'verbose_name_plural': 'Robot applications under test'},
        ),
        migrations.AlterField(
            model_name='robotapplicationundertest',
            name='robot_location',
            field=models.CharField(help_text='Provide the path to the local robot executable to use when running  the tests for this application.', max_length=200),
        ),
        migrations.AlterField(
            model_name='robottestsuite',
            name='parent',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_suite', related_query_name='parent_suite', to='testrunner.RobotTestSuite'),
        ),
    ]
