# Generated by Django 2.1.7 on 2019-02-19 07:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTest',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testrunner.BaseObject')),
                ('documentation', models.TextField(max_length=4000, null=True)),
            ],
            bases=('testrunner.baseobject',),
        ),
        migrations.CreateModel(
            name='RobotTestRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('pass', 'PASS'), ('fail', 'FAIL'), ('error', 'ERROR')], help_text='The final result of the test execution.', max_length=5)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='When test execution started.')),
                ('end_time', models.DateTimeField(help_text='When test execution ended.')),
                ('execution_time', models.TimeField()),
                ('status', models.CharField(choices=[('not started', 'Not Started'), ('in progress', 'In Progress'), ('complete', 'Complete'), ('error', 'Error')], help_text='The current status of this test run.', max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Why the test run has the current status.', max_length=400)),
                ('robot_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testrunner.RobotTest')),
            ],
        ),
        migrations.CreateModel(
            name='RobotTestStep',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testrunner.BaseObject')),
                ('keyword', models.CharField(max_length=200)),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='execution order')),
                ('arguments', models.TextField(help_text='A pipe separated string of arguments passed to the test step keyword.', max_length=4000, null=True)),
                ('robot_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testrunner.RobotTest')),
            ],
            bases=('testrunner.baseobject',),
        ),
        migrations.CreateModel(
            name='RobotTestSuite',
            fields=[
                ('baseobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='testrunner.BaseObject')),
                ('documentation', models.TextField(max_length=4000, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_suite', related_query_name='parent_suite', to='testrunner.RobotTestSuite')),
            ],
            bases=('testrunner.baseobject',),
        ),
        migrations.RemoveField(
            model_name='test',
            name='baseobject_ptr',
        ),
        migrations.RemoveField(
            model_name='test',
            name='suite',
        ),
        migrations.RemoveField(
            model_name='testrun',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='baseobject_ptr',
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Designates when this thing was created.'),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Designates when this thing was last modified.'),
        ),
        migrations.AlterField(
            model_name='baseobject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.DeleteModel(
            name='TestRun',
        ),
        migrations.DeleteModel(
            name='TestSuite',
        ),
        migrations.AddField(
            model_name='robottest',
            name='robot_suite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', related_query_name='suite', to='testrunner.RobotTestSuite'),
        ),
    ]
