# Generated by Django 2.1.7 on 2019-02-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0002_auto_20190219_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotvariable',
            name='value',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='robotapplicationundertest',
            name='app_test_location',
            field=models.FilePathField(allow_files=False, allow_folders=True, editable=False, help_text='The local path to the directory that contains tests for this app.', max_length=200, path='C:\\\\Users\\\\mrose\\\\ws\\\\robotframework', recursive=True),
        ),
        migrations.AlterField(
            model_name='robotapplicationundertest',
            name='robot_location',
            field=models.FilePathField(editable=False, help_text='The local path to the robot executable to use when running the tests for this application.', match='^.*.exe.*$', max_length=200, path='C:\\\\Users\\\\mrose\\\\ws\\\\robotframework', recursive=True),
        ),
        migrations.AlterField(
            model_name='robottestsuite',
            name='suite_location',
            field=models.FilePathField(allow_folders=True, blank=True, editable=False, help_text='The local path to the directory or file that contains tests for this suite. Options to select this will populate after an application is selected and saved.', max_length=200, path='C:\\\\Users\\\\mrose\\\\ws\\\\robotframework', recursive=True),
        ),
    ]
