# Generated by Django 2.1.7 on 2019-02-20 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testrunner', '0003_auto_20190220_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='robottag',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_robot_tag', related_query_name='parent_application', to='testrunner.RobotApplicationUnderTest'),
        ),
        migrations.AddField(
            model_name='robotvariable',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_robot_variable', related_query_name='parent_application', to='testrunner.RobotApplicationUnderTest'),
        ),
    ]
